### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by MaxPeal** [client9/shlib#26]
@client9 are you actively maintaining this lib?
If not, I would be happy to do so.

**Comment by syntaqx** [comment]
There are a few of us that have maintainer status for this project, but unfortunately it seems we are all preoccupied in life and haven't been able to provide the support that the project deserves.

We'd love your help if you'd like to jump in. I think the best way to start would be to start commenting on existing issues and pull requests so that we can get a gauge of your approach to existing problems and how you communicate. I see that you have an open pull request and will get that merged in short order.

I will make a specific effort to help you with mergers and questions while you're helping out, please @ me directly for any help you need, and once you've proven a minimal level of activity and ability I'd be happy to +1 you being added.

Hope we'll see good things from you! Get involved, and I hope to see more of you.

**Comment by syntaqx** [comment]
You're all merged in, and I've updated things as much as I can for the time being. Going to close this out for the time being, but feel free to let me know if I need to re-open for any particular reason.

**Comment by MaxPeal** [comment]
@syntaqx ok sounds good!
i will ping you with fixes / PR.
and if its sounds good for you in the longterm also to commit to the Project.

**Comment by MaxPeal** [comment]
@syntaqx have you time to take a look on the travis error?
if not, let me know and i will make a fix PR

**Comment by syntaqx** [comment]
Nope, feel free to open a new ticket describing the issue and then open a PR against the new issue #
